package gov.mm.covid19statsbago.generals

object UtilFont {
    fun convertCountryName(word: String): String {
        return word
            .replace("Brazil", "ဘရာဇီး")
            .replace("Germany", "ဂျာမနီ")
            .replace("Nigeria", "နိုင်ဂျီးရီးယား")
            .replace("Timor-Leste", "တီမော - လက်စ်တီ")
            .replace("Dominican Republic", "ဒိုမီနီကန်သမ္မတနိုင်ငံ")
            .replace("Portugal", "ပေါ်တူဂီ")
            .replace("Uganda", "ယူဂန်ဒါ")
            .replace("Mexico", "မက္ကစီကို")
            .replace("Moldova", "မော်လ်ဒိုဗာ")
            .replace("Palau", "ပလောင်")
            .replace("Palestinian Territory", "ပါလက်စတိုင်းနယ်မြေ")
            .replace("Ghana", "ဂါနာ")
            .replace("Angola", "အင်ဂိုလာ")
            .replace("Bangladesh", "ဘင်္ဂလားဒေ့ရှ်")
            .replace("Central African Republic", "ဗဟိုအာဖရိကသမ္မတနိုင်ငံ")
            .replace("China","တရုတ်")
            .replace("Fiji", "ဖီဂျီ")
            .replace("Guinea-Bissau", "ဂီနီ")
            .replace("Indonesia", "အင်ဒိုနီးရှား")
            .replace(" Malta", "မော်လတာ")
            .replace("Cook Islands", "ကွတ်ကျွန်းများ")
            .replace("Eritrea", "အီရီထရီးယား")
            .replace("Jersey", "ဂျာစီ")
            .replace("Mauritania", "Mauritania")
            .replace("Panama", "ပနားမား")
            .replace("Poland", "ပိုလန်")
            .replace("Argentina", "အာဂျင်တီးနား")
            .replace("Brunei Darussalam", "ဘရူနိုင်း")
            .replace("Ethiopia", "အီသီယိုးပီးယား")
            .replace("Honduras", "ဟွန်ဒူးရပ်စ်")
            .replace("United States of America", "အမေရိကန်")
            .replace("Congo (Kinshasa)", "ကွန်ဂို (ကင်ရှာဆာ)")
            .replace("Hong Kong", "ဟောင်ကောင်")
            .replace("Syrian Arab Republic (Syria)", "ဆီးရီးယားအာရပ်သမ္မတနိုင်ငံ (ဆီးရီးယား)")
            .replace("Antarctica", "အန္တာတိကတိုက်")
            .replace("Bulgaria", "ဘူဂေးရီးယား")
            .replace("Latvia", "လတ်ဗီးယား")
            .replace("Romania", "ရိုမေးနီးယား")
            .replace("Republic of Kosovo", "ကိုဆိုဗိုသမ္မတနိုင်ငံ")
            .replace("Lithuania", "လစ်သူယေးနီးယား")
            .replace("Saudi Arabia", "ဆော်ဒီအာရေဗျ")
            .replace("Korea (North)", "မြောက်ကိုးရီးယား ")
            .replace("Mauritius", "Mauritius")
            .replace("Cuba", "ကျူးဘား")
            .replace("Kyrgyzstan", "ကာဂျစ္စတန်")
            .replace("Malaysia", "မလေးရှား")
            .replace("Marshall Islands", "မာရှယ်ကျွန်းစု")
            .replace("Oman", "အိုမန်")
            .replace("Norway", "နော်ဝေး")
            .replace("United Arab Emirates", "ယူအေအီး")
            .replace("Uruguay", "ဥရုဂွေး")
            .replace("Australia", "သြစတြေးလျ")
            .replace("Italy", "အီတလီ")
            .replace("Mayotte", "Mayotte")
            .replace("Northern Mariana Islands", "မြောက်ပိုင်းမာရီယာနာကျွန်းများ")
            .replace("Saint Pierre and Miquelon", "စိန့် Pierre နှင့် Miquelon")
            .replace("Bolivia", "ဘိုလီးဗီးယား")
            .replace("Saint Helena", "စိန့်ဟယ်လီနာ")
            .replace("South Georgia and the South Sandwich Islands", "တောင်ပိုင်းဂျော်ဂျီယာနှင့်တောင်ပိုင်း Sandwichကကျွန်းများ")
            .replace("Svalbard and Jan Mayen Islands", "Svalbard နှင့် Jan Mayen ကျွန်းများ")
            .replace("Thailand", "ထိုင်းနိုင်ငံ")
            .replace("US Minor Outlying Islands", "အမေရိကန်ပြင်ပကျွန်းများ")
            .replace("Peru", "ပီရူး")
            .replace("Barbados", "ဘာဘေးဒိုးစ်")
            .replace("Bouvet Island", "Bouvet ကျွန်း")
            .replace("Egypt", "အီဂျစ်")
            .replace("New Caledonia", "နယူးကယ်လီဒိုးနီးယား")
            .replace("San Marino", "စန်မာရီနို")
            .replace("Spain", "စပိန်")
            .replace("Croatia", "ခရိုအေးရှား")
            .replace("Djibouti", "ဂျီဘူတီ")
            .replace("El Salvador", "အယ်လ်ဆာဗေးဒေါ")
            .replace("Denmark", "ဒိန်းမတ်")
            .replace("Turkmenistan", "Turkmenistan")
            .replace("Guyana", "ဂိုင်ယာနာ")
            .replace("Niger", "နိုင်ဂျ")
            .replace("Russian Federation", "ရုရှားပြည်ထောင်စု")
            .replace("Saint-Martin (French part)", "စိန့်မာတင် (ပြင်သစ်အပိုင်း)")
            .replace("ALA Aland Islands", "ALA Aland ကျွန်းစု")
            .replace("Macao, SAR China", "မကာအို၊ တရုတ်နိုင်ငံ")
            .replace("Saint Lucia", "စိန့်လူစီယာ")
            .replace("Belarus", "ဘီလာရုစ်")
            .replace("Austria", "သြစတြီးယား")
            .replace("Azerbaijan", "အဇာဘိုင်ဂျန်")
            .replace("France", "ပြင်သစ်")
            .replace("Maldives", "မော်လ်ဒိုက်")
            .replace("Sierra Leone", "ဆီးရီးယားလီယွန်း")
            .replace("Sri Lanka", "သီရိလင်္ကာ")
            .replace("Armenia", "အာမေးနီးယား")
            .replace("Bahamas", "ဘဟားမား")
            .replace("Belgium", "ဘယ်လ်ဂျီယံ")
            .replace("Congo (Brazzaville)", "ကွန်ဂို (ဘရာဇီဗီးလ်)")
            .replace("Kuwait", "ကူဝိတ်")
            .replace("Vanuatu", "ဗနူတူး")
            .replace("Viet Nam", "ဗီယက်နမ်နိုင်ငံ")
            .replace("Belize", "ဘေလီဇ်")
            .replace("Georgia", "ဂျော်ဂျီယာ")
            .replace("Liberia", "လိုက်ဘေးရီးယား")
            .replace("Zimbabwe", "ဇင်ဘာဘွေ")
            .replace("Suriname", "ဆူရီနာ")
            .replace("British Indian Ocean Territory", "ဗြိတိသျှအိန္ဒိယသမုဒ္ဒရာနယ်မြေ")
            .replace("Cocos (Keeling) Islands", "ကိုကို (ကီလင်) ကျွန်းများ")
            .replace("Nepal", "နီပေါ")
            .replace("Qatar", "ကာတာ")
            .replace("Tajikistan", "တာဂျစ်ကစ္စတန်")
            .replace("Bermuda", "ဘာမြူဒါ")
            .replace("Mali", "မာလီ")
            .replace("Saint Kitts and Nevis", "စိန့်ကစ်နှင့်နီဗီစ်")
            .replace("Venezuela (Bolivarian Republic)", "ဗင်နီဇွဲလား (ဘိုလီးဗီးယားသမ္မတနိုင်ငံ)")
            .replace("Canada", "ကနေဒါ")
            .replace("Algeria", "အယ်လ်ဂျီးရီးယား")
            .replace("Kazakhstan", "ကာဇက်စတန်")
            .replace("Netherlands", "နယ်သာလန်")
            .replace("Nauru", "နော်ရူး")
            .replace("United Kingdom", "ယူနိုက်တက်ကင်းဒမ်း")
            .replace("Saint Vincent and Grenadines", "စိန့်ဗင်းဆင့်နှင့်ဂရီနဒင်း")
            .replace("Turks and Caicos Islands", "တူရကီနှင့် Caicos ကျွန်းမျာ")
            .replace("Ireland", "အိုင်ယာလန်")
            .replace("Montenegro", "မွန်တီနီဂရိုး")
            .replace("Nicaragua", "နီကာရာဂွာ")
            .replace("Serbia", "ဆားဘီးယား")
            .replace("Switzerland", "ဆွစ်ဇာလန်")
            .replace("Tunisia", "တူနီးရှား")
            .replace("Greece", "ဂရိ")
            .replace("Korea (South)", "ကိုးရီးယား (တောင်)")
            .replace("Grenada", "ဂရီနာဒါ")
            .replace("Guadeloupe", "ဂွာတီလူး")
            .replace("Guatemala", "ဂွာတီမာလာ")
            .replace("Sudan", "ဆူဒန်")
            .replace("Yemen", "ယီမင်")
            .replace("Somalia", "ဆိုမာလီယာ")
            .replace("Cameroon", "ကင်မရွန်း")
            .replace("Christmas Island", "ခရစ်စမတ်ကျွန်း")
            .replace("Colombia", "ကိုလံဘီယာ")
            .replace("Costa Rica", "ကော့စတာရီကာ")
            .replace("New Zealand", "နယူးဇီလန်")
            .replace("Uzbekistan", "ဥဇဘက်ကစ္စတန်")
            .replace("Bosnia and Herzegovina", "ဘော့စနီးယားနှင့်ဟာဇီဂိုဗီးနား")
            .replace("Holy See (Vatican City State)", "သန့်ရှင်းသောဘုရား (ဗာတီကန်စီးတီးပြည်နယ်)")
            .replace("India", "အိန္ဒိယ")
            .replace("Philippines", "ဖိလစ်ပိုင်")
            .replace("Chile", "ချီလီ")
            .replace("Lebanon", "လက်ဘနွန်")
            .replace("South Sudan", "တောင်ဆူဒန်")
            .replace("Iran, Islamic Republic of", "အီရန်, အစ္စလာမ်မစ်သမ္မတနိုင်ငံ")
            .replace("Japan", "ဂျပန်")
            .replace("Pakistan", "ပါကစ္စတန်")
            .replace("Jordan", "ဂျော်ဒန်")
            .replace("Luxembourg", "လူဇင်ဘတ်")
            .replace("Namibia", "နမီးဘီးယား")
            .replace("Cambodia", "ကမ္ဘောဒီးယား")
            .replace("Estonia", "အက်စ်တိုးနီးယား")
            .replace("Western Sahara", "အနောက်ပိုင်းဆာဟာရ")
            .replace("Greenland", "ဂရင်းလန်း")
            .replace("Guam", "ဂူအမ်")
            .replace("Guinea", "ဂီနီယာ")
            .replace("Slovakia", "စလိုဗက်ကီးယား")
            .replace("Tokelau", "တိုကျို")
            .replace("Madagascar", "မာဒါဂက်စကာ")
            .replace("South Africa", "တောင်အာဖရိက")
            .replace("Haiti", "ဟေတီ")
            .replace("Israel", "အစ္စရေး")
            .replace("Papua New Guinea", "ပါပူဝါနယူးဂီနီ")
            .replace("Tanzania, United Republic of", "တန်ဇန်းနီးယား, ယူနိုက်တက်သမ္မတနိုင်ငံ")
            .replace("British Virgin Islands", "ဗြိတိသျှဗာဂျင်းကျွန်းစု")
            .replace("Faroe Islands", "ဖာရိုးကျွန်းများ")
            .replace("Gabon", "ဂါဘွန်း")
            .replace("Mozambique", "မိုဇမ်ဘစ်")
            .replace("Virgin Islands, US", "ဗာဂျင်းကျွန်းများ၊ ယူအက်စ်")
            .replace("Cyprus", "ဆိုက်ပရပ်စ်")
            .replace("Ecuador", "အီကွေဒေါ")
            .replace("French Southern Territories", "ပြင်သစ်တောင်ပိုင်းနယ်မြေများ")
            .replace("Kenya", "ကင်ညာ")
            .replace("Albania", "အယ်လ်ဘေးနီးယား")
            .replace("Monaco", "မိုနာကို")
            .replace("Morocco", "မော်ရိုကို")
            .replace("Réunion", "ရီယွန်း")
            .replace("Slovenia", "ဆလိုဗေးနီးယား")
            .replace("Lesotho", "လီဆိုသို")
            .replace("Libya", "လစ်ဗျား")
            .replace("Bhutan", "ဘူတန်")
            .replace("Finland", "ဖင်လန်")
            .replace("French Guiana", "ပြင်သစ်ဂူယာနာ")
            .replace("Malawi", "မာလာဝီ")
            .replace("Solomon Islands", "ဆော်လမွန်ကျွန်းစု")
            .replace("Tuvalu", "တူဗာလူ")
            .replace("Bahrain", "ဘာရိန်း")
            .replace("Chad", "ချဒ်")
            .replace("Equatorial Guinea", "အီကွေတာဂီနီ")
            .replace("Jamaica", "ဂျမေကာ")
            .replace("Micronesia, Federated States of", "မီခရိုနီးရှား၊")
            .replace("Mongolia", "မွန်ဂိုလီးယား")
            .replace("Sweden", "ဆွီဒင်နိုင်ငံ")
            .replace("Botswana", "ဘော့ဆွာနာ")
            .replace("Burundi", "ဘူရွန်ဒီ")
            .replace("Czech Republic", "ချက်သမ္မတနိုင်ငံ")
            .replace("French Polynesia", "ပြင်သစ်ပိုလီနီးရှား")
            .replace("Rwanda", "ရဝမ်ဒါ")
            .replace("Taiwan, Republic of China", "ထိုင်ဝမ်၊ တရုတ်သမ္မတနိုင်ငံ")
            .replace("Dominica", "ဒိုမီနီကာ")
            .replace("Lao PDR", "လာအို")
            .replace("Samoa", "ဆာမိုအာ")
            .replace("Swaziland", "ဆွာဇီလန်")
            .replace("Ukraine", "ယူကရိန်း")
            .replace("Andorra", "အန်ဒိုရာ")
            .replace("Antigua and Barbuda", "Antigua နှင့် Barbuda")
            .replace("Benin", "ဘီနင်")
            .replace("Cape Verde", "ကိပ် Verde")
            .replace("Niue", "နီယို")
            .replace("Afghanistan", "အာဖဂန်နစ္စတန်")
            .replace("Gambia", "ဂမ်ဘီယာ")
            .replace("Hungary", "ဟန်ဂေရီ")
            .replace("Turkey", "တူရကီ")
            .replace("Zambia", "ဇမ်ဘီယာ")
            .replace("Norfolk Island", "Norfolk ကျွန်း")
            .replace("Singapore", "စင်္ကာပူ")
            .replace("Cayman Islands", "ကေမန်ကျွန်းစု")
            .replace("Myanmar", "မြန်မာ")
            .replace("Netherlands Antilles", "နယ်သာလန်အန်တီ")
            .replace("Heard and Mcdonald Islands", "Heard နှင့် Mcdonald ကျွန်းများ")
            .replace("Paraguay", "ပါရာဂွေး")
            .replace("Wallis and Futuna Islands", "Wallis နှင့် Futuna ကျွန်းများ")
            .replace("Iraq", "အီရတ်")
            .replace("Macedonia, Republic of", "မက်ဆီဒိုးနီးယားသမ္မတနိုင်ငံ")
            .replace("American Samoa", "အမေရိကန်ဆာမိုအာ")
            .replace("Iceland", "အိုက်စလန်")
            .replace("Senegal", "ဆီနီဂေါ")
            .replace("Gibraltar", "ဂျီဘရောလ်")
            .replace("Kiribati", "ကီရီဘာတီ")
            .replace("Montserrat", "မွန်ဆာရတ်")
            .replace("Seychelles", "Seychelles")
            .replace("Trinidad and Tobago", "ထရီနီဒက်နှင့်တိုဘာဂို")
    }
    fun convertUniNumber(word: String): String {
        return word.toLowerCase()
            .replace('1', '၁')
            .replace('2', '၂')
            .replace('3', '၃')
            .replace('4', '၄')
            .replace('5', '၅')
            .replace('6', '၆')
            .replace('7', '၇')
            .replace('8', '၈')
            .replace('9', '၉')
            .replace('0', 'ဝ')
    }
    fun convertEngNumber(word: String): String {
        return word.toLowerCase()
            .replace('၁', '1')
            .replace('၂', '2')
            .replace('၃', '3')
            .replace('၄', '4')
            .replace('၅', '5')
            .replace('၆', '6')
            .replace('၇', '7')
            .replace('၈', '8')
            .replace('၉', '9')
            .replace('ဝ', '0')
    }
    fun convertMMDate(word: String): String {
        return "( "+word.toLowerCase().substring(8,10).toString().toUniNumber()+"/"+word.toLowerCase().substring(5,7).toString().toUniNumber()+"/"+word.toLowerCase().substring(0,4).toString().toUniNumber()+" )"

    }
}

fun String.toMMDate() = UtilFont.convertMMDate(this)

fun String.toUniNumber() = UtilFont.convertUniNumber(this)

fun String.toUniCountryName() = UtilFont.convertCountryName(this)

fun String.toEnglishNumber() = UtilFont.convertEngNumber(this)

fun Int.toUniNumber() = toString().toUniNumber()

fun Int.toEnglishNumber() = toString().toEnglishNumber()
